"""FastAPI application factory (Phase 4).

Every other Phase 4 API plan builds on `create_app()`: it mounts all seven
/api routers up front (six as empty stubs their owning plans fill) so later
plans only add routes to files they own, and it conditionally serves the
built React frontend from web/dist when that directory exists (plan 04-11
fills it; tests and bare-backend runs never require a frontend build).

No cross-origin middleware by design: the frontend is served same-origin
from this app in production and via a Vite dev proxy in development
(private-network, no-auth — PROJECT.md delivery constraints).
"""

from pathlib import Path

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from huntloop.api.routers import (
    companies,
    criteria,
    dashboard,
    diagnostics,
    jobs,
    onboarding,
    runs,
    settings,
)


def create_app() -> FastAPI:
    app = FastAPI(title="HuntLoop API")

    @app.get("/api/health")
    def health() -> dict[str, str]:
        return {"status": "ok"}

    app.include_router(criteria.router)
    app.include_router(companies.router)
    app.include_router(jobs.router)
    app.include_router(runs.router)
    app.include_router(dashboard.router)
    app.include_router(settings.router)
    app.include_router(diagnostics.router)
    # The eighth router: onboarding proposals (INTK-05) landed by plan 04-03.
    # Additive include only — plans 04-04..04-06 do not edit this file.
    app.include_router(onboarding.router)

    # Serve the built frontend only when it exists. The guard keeps tests and
    # bare-backend runs independent of any frontend build (plan 04-11 fills
    # web/dist; 04-11's Dockerfile stage lands dist at /app/web/dist).
    dist = _frontend_dist()
    if dist is not None:
        app.mount("/", StaticFiles(directory=dist, html=True), name="web")

    return app


def _frontend_dist() -> Path | None:
    """Locate the built SPA (plan 04-11), or None when it has not been built.

    Two locations are checked because the package is installed differently per
    environment, and the Docker image is the deployment target this exists for:

    - ``parents[3]/web/dist`` is the repo root in a source checkout (editable
      installs, local ``uvicorn``/``pytest``) — ``src/huntloop/api/app.py`` is
      three directories below the root.
    - ``cwd/web/dist`` is where the Docker image lands the SPA. The runtime
      stage ``pip install``s the package into site-packages (so ``__file__``
      resolves under ``site-packages`` and the repo-root candidate misses), but
      the image ``WORKDIR`` is ``/app`` and the node stage's output is copied to
      ``/app/web/dist``.

    The first existing match wins; a missing directory means "no frontend build
    here" and the app serves API only, exactly as before plan 04-11.
    """
    candidates = (
        Path(__file__).resolve().parents[3] / "web" / "dist",
        Path.cwd() / "web" / "dist",
    )
    for candidate in candidates:
        if candidate.is_dir():
            return candidate
    return None
