"""initial main schema

Revision ID: 8c3c9b5a42ab
Revises: 
Create Date: 2026-09-09 15:36:22.360285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c3c9b5a42ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ats', sa.Enum('GREENHOUSE', 'LEVER', 'ASHBY', 'WORKDAY', 'SMARTRECRUITERS', 'FIRECRAWL', 'UNKNOWN', name='ats_platform', native_enum=False), nullable=True),
    sa.Column('ats_identifier', sa.Text(), nullable=True),
    sa.Column('ats_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('careers_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_job_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_empty_runs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_companies_name')
    )
    op.create_table('criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.Enum('INITIAL', 'PROPOSAL_ACCEPTED', 'MANUAL_EDIT', name='criteria_source', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_criteria_version')
    )
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.create_index('uq_criteria_single_active', ['is_active'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))

    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.Enum('SCHEDULED', 'MANUAL', name='run_trigger', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='run_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('companies_checked', sa.Integer(), nullable=False),
    sa.Column('listings_fetched', sa.Integer(), nullable=False),
    sa.Column('after_dedup', sa.Integer(), nullable=False),
    sa.Column('after_deterministic', sa.Integer(), nullable=False),
    sa.Column('after_triage', sa.Integer(), nullable=False),
    sa.Column('scored', sa.Integer(), nullable=False),
    sa.Column('new_jobs_written', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.CheckConstraint('NOT (is_secret AND value IS NOT NULL)', name='ck_settings_secret_value_null'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('criteria_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('based_on_run_id', sa.Uuid(), nullable=True),
    sa.Column('proposed_changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('predicted_effect', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='proposal_status', native_enum=False), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resulting_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['based_on_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['resulting_version'], ['criteria.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('location_normalized', sa.Text(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('remote_scope', sa.Enum('GLOBAL', 'REGION', 'COUNTRY', 'UNSPECIFIED', name='remote_scope', native_enum=False), nullable=True),
    sa.Column('location_eligible', sa.Boolean(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comp_raw', sa.Text(), nullable=True),
    sa.Column('comp_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comp_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comp_currency', sa.Text(), nullable=True),
    sa.Column('comp_period', sa.Enum('ANNUAL', 'MONTHLY', 'HOURLY', 'UNSPECIFIED', name='comp_period', native_enum=False), nullable=True),
    sa.Column('work_auth_required', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SHORTLISTED', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN', name='job_status', native_enum=False), nullable=False),
    sa.Column('score_overall', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('score_dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('score_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('score_summary', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_criteria_version', sa.Integer(), nullable=True),
    sa.Column('scored_rubric_version', sa.Text(), nullable=True),
    sa.Column('scored_with_model', sa.Text(), nullable=True),
    sa.Column('filter_tier_reached', sa.Enum('DETERMINISTIC', 'TRIAGE', 'FULL', name='filter_tier', native_enum=False), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('source_run_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_jobs_dedup_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_jobs_score_overall', ['score_overall'], unique=False)
        batch_op.create_index('ix_jobs_status', ['status'], unique=False)

    op.create_table('run_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_errors', schema=None) as batch_op:
        batch_op.create_index('ix_run_errors_run_id', ['run_id'], unique=False)

    op.create_table('feedback_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('CHAT', 'JOB_NOTE', name='feedback_source', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('NEW', 'SHORTLISTED', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN', name='status_event_from_status', native_enum=False), nullable=True),
    sa.Column('to_status', sa.Enum('NEW', 'SHORTLISTED', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN', name='status_event_to_status', native_enum=False), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('USER', 'SYSTEM', name='status_event_source', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index('ix_status_events_job_id', ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index('ix_status_events_job_id')

    op.drop_table('status_events')
    op.drop_table('feedback_notes')
    with op.batch_alter_table('run_errors', schema=None) as batch_op:
        batch_op.drop_index('ix_run_errors_run_id')

    op.drop_table('run_errors')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status')
        batch_op.drop_index('ix_jobs_score_overall')
        batch_op.drop_index('ix_jobs_company_id')

    op.drop_table('jobs')
    op.drop_table('criteria_proposals')
    op.drop_table('settings')
    op.drop_table('runs')
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.drop_index('uq_criteria_single_active', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))

    op.drop_table('criteria')
    op.drop_table('companies')
    # ### end Alembic commands ###
